### ISSUE TITLE
libopenni-dev missing in Saucy repo

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/reprepro-updater#13]
http://ec2-54-67-30-249.us-west-1.compute.amazonaws.com:8080/view/IrelUbu/job/IrelUbu__openni_camera__ubuntu_saucy_amd64__binary/1/console

**Comment by dirk-thomas** [comment]
The new rule is insufficient. The following job still fails: http://54.183.26.131:8080/job/Ibin_uS64__openni_camera__ubuntu_saucy_amd64__binary/2/console

After looking into the recursive dependencies it looks like it is missing `openni-utils`.

**Comment by tfoote** [comment]
added openni-utils to the import rule and tested after running the import as installable.
