### ISSUE TITLE
Ignition Edifice import failed: lack of one of the physics4 packages

### ISSUE THREAD

**Issue by j-rivero** [ros-infrastructure/reprepro-updater#133]
After https://github.com/ros-infrastructure/reprepro-updater/pull/131 the import of Ignition Edifice was not complete, failing with the error:

```
$ aptitude install ignition-edifice
...
The following packages have unmet dependencies:
 libignition-physics4-dev : Depends: libignition-physics4-heightmap-dev (= 4.3.0-1~focal) which is a virtual package and is not provided by any available package

 libignition-physics4-dartsim-dev : Depends: libignition-physics4-heightmap-dev (= 4.3.0-1~focal) which is a virtual package and is not provided by any available package

The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     libignition-physics4-dartsim-dev [Not Installed]   
2)     libignition-physics4-dev [Not Installed]    
```
`libignition-physics4-heightmap-dev` [was missing from the import ](https://build.ros2.org/job/import_upstream/346/consoleFull) but nor our CI nor our importer (really the same aptly calls) was not able to detect it. It is being listed a standard `Depends:` of `libignition-physics4-dartsim-dev` listed in the config file. 

reported by @luca-della-vedova  @chapulina

**Comment by chapulina** [comment]
For completeness, the `bullet` component is also missing, but it's not causing issues because it isn't required

**Comment by chapulina** [comment]
Fixed!
