### ISSUE TITLE
Add link to the each package's wiki page in the release announcement

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/reprepro-updater#36]
People click when there's a link (unconfirmed fact).

Joking aside, linking to each page is not only beneficial for readers to save a few (dozens of) seconds to reach the package's page, but hopefully also help reminding for the packages whose wiki page isn't yet generated. To better achieve the latter, only for those packages where pages already exist can be linked so that packages-without-page become obvious.

I like to provide PR whenever I can but if someone likes the idea and can work on please go ahead.

**Comment by tfoote** [comment]
Fixed in #53
