### ISSUE TITLE
scripts/setup_repo.py ubuntu_testing -q returns success when gpg key setup is invalid

### ISSUE THREAD

**Issue by nuclearsandwich** [ros-infrastructure/reprepro-updater#45]
Observed while setting up the ROS 2 testfarm, this query guards the first time setup of the reprepo repository structure via puppet (`reprepro-updater/scripts/setup_repo.py ubuntu_{building,main,testing} -c`) but the repository is only partially configured due to bad gpg key configuration.

This issue is with the refactor branch.

/cc @tfoote

**Comment by nuclearsandwich** [comment]
As a side note that should probably just be a separate issue but I'm lazy, setup_repo.py should also call clearvanished.

**Comment by dirk-thomas** [comment]
Is this similar to #49?

**Comment by tfoote** [comment]
Yes, i think it may be covered by that. I'll check when I review I will confirm it's covering this error too.

**Comment by tfoote** [comment]
This is covered by #49

**Comment by nuclearsandwich** [comment]
Should we close this in favor of #49 then?

**Comment by tfoote** [comment]
resolved in #49
